# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KoHqOJ2aO5yR1VT_HJX-Nv3VXxBTto4
"""

import matplotlib.pyplot as plt

import numpy as np

x = np.array([0,1,2,3,4,5])

y = np.array([0,2,8,1,14,7])

plt.scatter(x,y,color='red')

x = np.array([12,6,8,11,8,3])

y = np.array([5,6,3,7,17,19])

plt.scatter(x,y,color='green')

plt.show()

import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(0, 2 * np.pi, 1000)

y = np.sin(t)
plt.figure(figsize=(8, 6))
plt.plot(t, y, label='y = sin(t)', color='blue')
plt.title("Sinus Funksiyasining Grafigi")
plt.xlabel("t o'qi")
plt.ylabel("y o'qi")
plt.axhline(0, color='black', linewidth=0.8)
plt.axvline(0, color='black', linewidth=0.8)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AF")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AZ")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AD")]
print(filtr)

from google.colab.patches import cv2_imshow
import cv2

rasm = cv2.imread('/content/malibu.jpg')

cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)